name: Publish

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: ['main']

permissions: read-all

jobs:
  build-test-lint:
    name: Build & Test & Lint
    uses: ./.github/workflows/build-test-lint.yml
    permissions: read-all
  publish:
    name: Publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['8.0', '9.0']
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Pack
        run: dotnet pack
      - name: Publish
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/microsoft/index.json --skip-duplicate --no-symbols
